### ISSUE TITLE
Domestic payment Funds confirmation fails

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#714]
Domestic payment funds confirmation fails with the below error:

```shell
2022-12-15 10:33:11.406 DEBUG 1 --- [nio-8080-exec-1] .f.s.o.u.r.w.DisabledEndpointInterceptor : Request URI /backoffice/payment-funds-confirmation/null is not disabled in RS config. Allowed to proceed.
2022-12-15 10:34:07.385 DEBUG 1 --- [nio-8080-exec-4] .f.s.o.u.r.w.DisabledEndpointInterceptor : Request URI /admin/data/user/has-data is not disabled in RS config. Allowed to proceed.
2022-12-15 10:34:43.180 DEBUG 1 --- [nio-8080-exec-6] .f.s.o.u.r.w.DisabledEndpointInterceptor : Request URI /backoffice/payment-funds-confirmation/null is not disabled in RS config. Allowed to proceed.
2022-12-15 10:34:43.183 DEBUG 1 --- [nio-8080-exec-6] c.f.s.o.u.r.s.b.BalanceStoreService      : Read balances for account null
2022-12-15 10:34:43.194 ERROR 1 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: No balance found of type 'InterimAvailable' for account id 'null'] with root cause
java.lang.IllegalStateException: No balance found of type 'InterimAvailable' for account id 'null'
	at com.forgerock.securebanking.openbanking.uk.rs.service.balance.FundsAvailabilityService.lambda$isFundsAvailable$0(FundsAvailabilityService.java:53) ~[securebanking-openbanking-uk-rs-simulator-server-1.1.5-SNAPSHOT.jar!/:na]
	at java.base/java.util.Optional.orElseThrow(Unknown Source) ~[na:na]
```

**Comment by jorgesanchezperez** [comment]
The account Id is null, because the consent decision process updates the debtor field consent, and the accountId field still null.

**Comment by jorgesanchezperez** [comment]
In all payment routes we have the below filters:
```json
{
          "comment": "Fetch Open Banking consent from IDM to get the resource owner id",
          "name": "GetResourceOwnerIdFromConsent",
          "type": "ScriptableFilter",
          "config": {
            "type": "application/x-groovy",
            "file": "GetResourceOwnerIdFromConsent.groovy",
            "clientHandler": "IDMClientHandler",
            "args": {
              "routeArgIdmBaseUri": "https://&{identity.platform.fqdn}",
              "routeArgObjUser": "&{user.object}"
            }
          }
        },
        {
          "comment": "Adjust URL for downstream resource server",
          "name": "TranslatePaymentResource",
          "type": "ScriptableFilter",
          "config": {
            "type": "application/x-groovy",
            "file": "TranslatePaymentResource.groovy",
            "args": {
              "routeArgAccountIdHeader": "x-ob-account-id"
            }
          }
        },
```
`GetResourceOwnerIdFromConsent` to set the accountId as route attribute
TranslatePaymentResource to add headers to the request as x-fapi-interaction-id and x-ob-account-id with the value from the attribute added in the previous filter.
request.headers.add(routeArgAccountIdHeader, attributes.get("accountId"))
The accountId needs to be an Array of values


Jorge Sanchez-Perez
  [28 minutes ago](https://forgerock.slack.com/archives/C02TAGPPHKM/p1671439563447029?thread_ts=1671438269.384719&cid=C02TAGPPHKM)
The accountId is null or empty, in payments that have the operation funds confirmation we have an issue regarding the accountId  where the value is null and we expected in the operation an account Id value. (edited)
