### ISSUE TITLE
Submission of VRP Payment results in 500 (Internal Server Error)

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#982]
Version: 1.0.1
Environment: ob-sandbox-v1
Fixed In: 

## Description
When submitting a Variable Recurring Payment a 500 (Internal Server Error) is received with the following body;

```
{
    "Code": "500",
    "Id": "0c289c6a43b573a6b1ecfa2968741f6d",
    "Message": "[Status: 500 Internal Server Error]",
    "Errors": [
        {
            "ErrorCode": "UK.OBIE.UnexpectedError",
            "Message": "Internal error [Internal Server Error]"
        }
    ]
}
```

## Steps to Reproduce
1. Perform DCR
2. Create a VRP Payment Consent
3. Perform hybrid flow and approve the Consent
4. Use the authorization_code grant to obtain an access token with consent
5. Submit a VRP Payment
### Expected Behaviour
Payment is created and a 201 (Created) result is returned.
### Actual Behavior
A 500 error is returned as explained in the Description Section

**Comment by BohoCode** [comment]
From the logs;

```
java.lang.NullPointerException: Cannot invoke "uk.org.openbanking.datamodel.vrp.OBDomesticVRPInstruction.getCreditorAccount()" because "instruction" is null
	at com.forgerock.sapi.gateway.ob.uk.common.datamodel.converter.vrp.FRDomesticVrpConverters.toFRDomesticVRPInstruction(FRDomesticVrpConverters.java:67) ~[secure-api-gateway-ob-uk-common-datamodel-1.0.2.jar!/:na]
	at com.forgerock.sapi.gateway.ob.uk.common.datamodel.converter.vrp.FRDomesticVrpConverters.toFRDomesticVRPRequestData(FRDomesticVrpConverters.java:61) ~[secure-api-gateway-ob-uk-common-datamodel-1.0.2.jar!/:na]
	at com.forgerock.sapi.gateway.ob.uk.common.datamodel.converter.vrp.FRDomesticVrpConverters.toFRDomesticVRPRequest(FRDomesticVrpConverters.java:47) ~[secure-api-gateway-ob-uk-common-datamodel-1.0.2.jar!/:na]
	at com.forgerock.sapi.gateway.ob.uk.rs.server.api.obie.payment.v3_1_9.vrp.DomesticVrpsApiController.domesticVrpPost(DomesticVrpsApiController.java:194) ~[classes!/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor1248.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.d…[message truncated due to size]
```

**Comment by BohoCode** [comment]
Jorge explained which bits I need to submit. My postman request was submitting stuff in the payment submission that didn't need to be submitted. 
I am now no longer getting a 500 error from this submission.
